version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: your-container-name
        restart: unless-stopped
        tty: true
        environment:
            APP_NAME: your-app-name
            APP_ENV: local
            APP_KEY: your-app-key
            APP_DEBUG: true
            APP_URL: http://localhost:8000
            LOG_CHANNEL: stderr
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: your-database-name
            DB_USERNAME: your-database-username
            DB_PASSWORD: your-database-password
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: mysql-container
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: your-database-name
            MYSQL_USER: your-database-username
            MYSQL_PASSWORD: your-database-password
            MYSQL_ROOT_PASSWORD: your-database-root-password
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password

    nginx:
        image: nginx:stable-alpine
        container_name: nginx-container
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    redis:
        image: redis:alpine
        container_name: redis-container
        restart: unless-stopped
        ports:
            - "6379:6379"

volumes:
    dbdata:
